version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-latest
      - build-1.16
      - build-1.17
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-latest
      - build-1.16
      - build-1.17

jobs:
  build-latest: &build-template
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run: go vet ./...
      - run:
          name: golint
          command: |
                    go get -u golang.org/x/lint/golint
                    golint -set_exit_status ./...
      - run:
          name: staticcheck.io
          command: |
                    go get honnef.co/go/tools/cmd/staticcheck
                    staticcheck -checks all ./...
      - run:
          name: Check gofumpt formatting
          command: |
                    go get mvdan.cc/gofumpt
                    gofumpt -d .
                    [ -z "$(gofumpt -l .)" ]
      - run: go build
      - run:
          name: Test matching (single file)
          command: |
                    for x in a b c d ; do
                      ./ip_compact test/$x.txt > got.txt
                      diff -Naur test/${x}_compact.txt got.txt
                      rm got.txt
                    done
      - run:
          name: Test matching (two files)
          command: |
                    for x in a b c d ; do
                      for y in a b c d ; do
                        ./ip_compact test/$x.txt test/$y.txt > got.txt
                        diff -Naur test/${x}_${y}_compact.txt got.txt
                        rm got.txt
                      done
                    done
      - run:
          name: Test matching (three files)
          command: |
                    for x in a b c d ; do
                      for y in a b c d ; do
                        for z in a b c d ; do
                          ./ip_compact test/$x.txt test/$y.txt test/$z.txt > got.txt
                          diff -Naur test/${x}_${y}_${z}_compact.txt got.txt
                          rm got.txt
                        done
                      done
                    done

  build-1.16:
    <<: *build-template
    docker:
      - image: circleci/golang:1.17

  build-1.17:
    <<: *build-template
    docker:
      - image: circleci/golang:1.17
